// <auto-generated />
namespace ExemploMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class algumas_atualizacoes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(algumas_atualizacoes));
        
        string IMigrationMetadata.Id
        {
            get { return "201711010353570_algumas_atualizacoes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
